import { getMeta } from '@fluch/signal-store/internal';
import { deriveActionName } from './derive-action-name';
import type {
  DevtoolsConnectOptions,
  DevtoolsInstance,
  ReduxDevtoolsExtension,
} from './redux-devtools-types';

const MONITOR_ONLY_FEATURES: NonNullable<DevtoolsConnectOptions['features']> = {
  pause: false,
  lock: false,
  persist: false,
  export: false,
  import: false,
  jump: false,
  skip: false,
  reorder: false,
  dispatch: false,
  test: false,
};

export type ConnectDevtoolsOptions = {
  /**
   * Instance label shown in the Redux DevTools UI. Defaults to `'signal-store'`.
   * Use distinct names when connecting multiple stores from the same app so
   * the DevTools instance picker can tell them apart.
   */
  name?: string;
  /**
   * Stable identifier for an instance — useful across HMR reloads to keep the
   * extension's panel attached to the same logical store. Auto-generated by
   * the extension when omitted.
   */
  instanceId?: string;
  /**
   * Max number of actions retained by the extension. Defaults to `50`.
   */
  maxAge?: number;
  /**
   * When `true` (default), derive the action label from the JS stack trace of
   * the `patchState` call. Set to `false` to label every action as
   * `STATE_UPDATE` — useful in production builds where minified function names
   * become unreadable, or to skip the (tiny) cost of building a stack.
   */
  trace?: boolean;
};

export type DevtoolsConnection = {
  /**
   * Stop relaying mutations to the extension. Safe to call multiple times.
   * Called automatically when the store is destroyed.
   */
  disconnect(): void;
};

/**
 * Bridge a signal-store instance to the Redux DevTools browser extension.
 *
 * Every {@link patchState} call publishes a synthetic action to the extension
 * (label derived from the call site by default — see {@link ConnectDevtoolsOptions.trace}),
 * along with the post-commit snapshot of the store's state. The extension then
 * shows the timeline, action log, state tree, and diff view.
 *
 * **Monitor-only.** This connector does not handle time-travel or dispatched
 * actions from the extension UI. JUMP_TO_STATE / JUMP_TO_ACTION / dispatcher
 * are explicit non-features of v2.x.
 *
 * **Production stripping.** Wrap the call site in an environment guard so the
 * import is tree-shaken out of production bundles:
 *
 * ```ts
 * if (import.meta.env.DEV) {
 *   connectDevtools(store, { name: 'Counter' });
 * }
 * ```
 *
 * **No-ops.** If the Redux DevTools extension is not installed, or the store
 * has already been destroyed, the call is a silent no-op returning a
 * `disconnect()` you can still call without effect.
 *
 * @param store — a store built via {@link signalStore}.
 * @param options — naming, history depth, tracing controls.
 * @throws if `store` is not a signal-store instance.
 *
 * @example
 * ```ts
 * import { signalStore, withState, withMethods, patchState } from '@fluch/signal-store';
 * import { connectDevtools } from '@fluch/signal-store-devtools';
 *
 * const counter = signalStore(
 *   withState({ count: 0 }),
 *   withMethods((s) => ({
 *     increment: () => patchState(s, { count: s.count.value + 1 }),
 *   })),
 * );
 *
 * if (import.meta.env.DEV) connectDevtools(counter, { name: 'Counter' });
 *
 * counter.increment(); // DevTools: action "increment", state { count: 1 }
 * ```
 */
export function connectDevtools(
  store: object,
  options: ConnectDevtoolsOptions = {},
): DevtoolsConnection {
  const meta = getMeta(store);
  if (meta === undefined) {
    throw new Error('connectDevtools requires a store built via signalStore(...)');
  }

  const noop: DevtoolsConnection = { disconnect: () => {} };

  if (meta.cleanup.closed) return noop;

  const ext = getExtension();
  if (ext === undefined) return noop;

  const trace = options.trace ?? true;

  const connectOptions: DevtoolsConnectOptions = {
    name: options.name ?? 'signal-store',
    maxAge: options.maxAge ?? 50,
    serialize: true,
    features: MONITOR_ONLY_FEATURES,
  };
  if (options.instanceId !== undefined) connectOptions.instanceId = options.instanceId;

  const conn: DevtoolsInstance = ext.connect(connectOptions);
  conn.init(meta.state$.value);

  const mutSub = meta.mutations$.subscribe(() => {
    const stack = trace ? new Error().stack : undefined;
    conn.send({ type: deriveActionName(stack) }, meta.state$.value);
  });

  meta.cleanup.add(mutSub);

  let disconnected = false;
  return {
    disconnect: () => {
      if (disconnected) return;
      disconnected = true;
      mutSub.unsubscribe();
      meta.cleanup.remove(mutSub);
    },
  };
}

function getExtension(): ReduxDevtoolsExtension | undefined {
  if (typeof globalThis === 'undefined') return undefined;
  const win = (globalThis as { window?: unknown }).window;
  if (typeof win !== 'object' || win === null) return undefined;
  const ext = (win as { __REDUX_DEVTOOLS_EXTENSION__?: ReduxDevtoolsExtension })
    .__REDUX_DEVTOOLS_EXTENSION__;
  return typeof ext === 'object' && ext !== null ? ext : undefined;
}
